spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/ticket_system?useUnicode=true&characterEncoding=UTF-8&createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
  jpa:
    hibernate:
      ddl-auto: update
